data_cfg:
#  input_dir: E:\dataset\Structured3D\
#  train_file: E:\python_project\OpenPanoDepth\datasets\structure3d\train_structure3d.txt
#  test_file: E:\python_project\OpenPanoDepth\datasets\structure3d\test_structure3d.txt
  input_dir: E:\\dataset\\2D3Ds
  train_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\train_stanford2d3d.txt
  test_file: E:\\python_project\\OpenPanoDepth\\datasets\\stanford2d3d\\test_stanford2d3d.txt
  name: stanford2d3d
  train_batch_size: 2
  test_batch_size: 2
  shuffle: True
  num_workers:  8
  type: low

model_cfg:
  model: IGEV_Bifuse
#  load_checkpoint: E:\\python_project\\OpenPanoDepth\\result\\IGEV_Bifuse_loss0.9\\checkpoints\\checkpoint_best.pth
  load_checkpoint: None

  base_config:
    hidden_dims: 512
    iters: 10
    bifuse_config:
      save_path: E:\\python_project\\OpenPanoDepth\\result\\IGEV_Bifuse_loss0.7
      dnet_args:
        layers: 34
        nbins: 100
        min_val: 0.1
        max_val: 10
        nrows: 4
        npatches_dict: { 3: 10, 4: 18, 5: 26, 6: 46 }
        patch_size: 128
        fov: 80

    hohonet_config:
      emb_dim: 256

      backbone_config:
          module: HarDNet
          kwargs:
            depth_wise: False
            arch: 68
            pretrained: True

      decode_config:
          module: EfficientHeightReduction

      refine_config:
          module: TransEn
          kwargs:
            position_encode: 128
            num_layers: 1

      upsample_config:
          module: Upsample1D

      modalities_config:
          DepthEstimator:
            basis: dct
            n_components: 64
            loss: l1



worker_cfg:
  epochs: 100
  visualize_interval: 20
  save_checkpoint: E:\\python_project\\OpenPanoDepth\\result\\IGEV_Bifuse_loss0.7\\checkpoints
  save_path: E:\\python_project\\OpenPanoDepth\\result\\IGEV_Bifuse_loss0.7

  optimizer_cfg:
    solver: AdamW
    lr: 0.0002
    betas: (0.9, 0.999)
    weight_decay: 0.01

  scheduler_cfg:
    T_0: 5
    T_mult: 2
    eta_min: 1e-6
    last_epoch: -1


  evaluator_cfg:
    metric:
      - abs_
      - abs_rel
      - sq_rel
      - rms
      - rms_log
      - log10
      - a1
      - a2
      - a3